const builtin = @import("builtin");
const std = @import("std");
const Builder = @import("std").build.Builder;

pub fn build(b: *Builder) !void {
    const mode = b.standardReleaseOptions();
    const want_gdb = b.option(bool, "gdb", "Build for using gdb with qemu") orelse false;

    const arch = builtin.Arch{ .thumb = .v8m_mainline };

    // The utility program for creating a CMSE import library
    // -------------------------------------------------------
    const mkimplib = "../target/debug/tzmcfi_mkimplib";

    // The Secure part
    // -------------------------------------------------------
    const exe_s_name = if (want_gdb) "secure-dbg" else "secure";
    const exe_s = b.addExecutable(exe_s_name, "secure.zig");
    exe_s.setLinkerScriptPath("secure/linker.ld");
    exe_s.setTarget(arch, .freestanding, .eabi);
    exe_s.setBuildMode(mode);
    exe_s.addAssemblyFile("common/startup.s");
    exe_s.setOutputDir("zig-cache");
    // TODO: exe_s.addPackagePath("tzmcfi-monitor", "../src/monitor.zig");
    exe_s.addPackagePath("arm_cmse", "../src/drivers/arm_cmse.zig");
    exe_s.addPackagePath("arm_m", "../src/drivers/arm_m.zig");

    // CMSE import library (generated from the Secure binary)
    // -------------------------------------------------------
    // It includes the absolute addresses of Non-Secure-callable functions
    // exported by the Secure code. Usually it's generated by passing the
    // `--cmse-implib` option to a supported version of `arm-none-eabi-gcc`, but
    // since it might not be available, we use a custom tool to do that.
    const implib_path = "zig-cache/secure_implib.s";
    var implib_args = std.ArrayList([]const u8).init(b.allocator);
    try implib_args.appendSlice([_][]const u8{
        mkimplib,
        exe_s.getOutputPath(),
        "-o",
        implib_path,
    });

    const implib = b.addSystemCommand(implib_args.toSliceConst());
    implib.step.dependOn(&exe_s.step);

    const implib_step = b.step("implib", "Create a CMSE import library");
    implib_step.dependOn(&implib.step);

    // FreeRTOS (This runs in Non-Secure mode)
    // -------------------------------------------------------
    const kernel_name = if (want_gdb) "freertos-dbg" else "freertos";
    const kernel = b.addStaticLibrary(kernel_name, "freertos.zig");
    kernel.setTarget(arch, .freestanding, .eabi);
    kernel.setBuildMode(mode);

    const kernel_include_dirs = [_][]const u8 {
        "freertos/include",
        "freertos/portable/GCC/ARM_CM33/non_secure",
        "freertos/portable/GCC/ARM_CM33/secure",
        "nonsecure", // For `FreeRTOSConfig.h`
    };
    for (kernel_include_dirs) |path| {
        kernel.addIncludeDir(path);
    }

    const kernel_source_files = [_][]const u8 {
        "freertos/croutine.c",
        "freertos/event_groups.c",
        "freertos/list.c",
        "freertos/queue.c",
        "freertos/stream_buffer.c",
        "freertos/tasks.c",
        "freertos/timers.c",
        "freertos/portable/GCC/ARM_CM33/non_secure/port.c",
        "freertos/portable/GCC/ARM_CM33/non_secure/portasm.c",
        "freertos/portable/MemMang/heap_4.c",
    };
    for (kernel_source_files) |file| {
        kernel.addCSourceFile(file, [_][]const u8 {});
    }

    // The Non-Secure part
    // -------------------------------------------------------
    const exe_ns_name = if (want_gdb) "nonsecure-dbg" else "nonsecure";
    const exe_ns = b.addExecutable(exe_ns_name, "nonsecure.zig");
    exe_ns.setLinkerScriptPath("nonsecure/linker.ld");
    exe_ns.setTarget(arch, .freestanding, .eabi);
    exe_ns.setBuildMode(mode);
    exe_ns.addAssemblyFile("common/startup.s");
    exe_ns.setOutputDir("zig-cache");

    for (kernel_include_dirs) |path| {
        exe_ns.addIncludeDir(path);
    }
    exe_ns.linkLibrary(kernel);
    exe_ns.addCSourceFile("nonsecure/oshooks.c", [_][]const u8 {});

    exe_ns.addAssemblyFile(implib_path);
    exe_ns.step.dependOn(&implib.step);

    const exe_both = b.step("build", "Build Secure and Non-Secure executables");
    exe_both.dependOn(&exe_s.step);
    exe_both.dependOn(&exe_ns.step);

    // Launch QEMU
    // -------------------------------------------------------
    const qemu = b.step("qemu", "Run the program in qemu");
    var qemu_args = std.ArrayList([]const u8).init(b.allocator);

    const qemu_device_arg = try std.fmt.allocPrint(
        b.allocator,
        "loader,file={}",
        exe_ns.getOutputPath(),
    );
    try qemu_args.appendSlice([_][]const u8{
        "qemu-system-arm",
        "-kernel",
        exe_s.getOutputPath(),
        "-device",
        qemu_device_arg,
        "-machine",
        "mps2-an505",
        "-nographic",
        "-d",
        "guest_errors",
        "-semihosting",
        "-semihosting-config",
        "target=native",
        "-s",
    });
    if (want_gdb) {
        try qemu_args.appendSlice([_][]const u8{ "-S" });
    }
    const run_qemu = b.addSystemCommand(qemu_args.toSliceConst());
    qemu.dependOn(&run_qemu.step);
    run_qemu.step.dependOn(exe_both);

    // Default Rule
    // -------------------------------------------------------
    b.default_step.dependOn(exe_both);
}
