#pragma once

#define TC_VEC_TABLE_HDR_SIGNATURE          0xf4510000
#define TC_VEC_TABLE_HDR_SIGNATURE_MASK     0xffff0000
#define TC_VEC_TABLE_HDR_SIZE_MASK          0x0000ffff

#define TC_VEC_TABLE_TRAMPOLINE_STRIDE      16
