[package]
name = "tzmcfi_patch"
version = "0.1.0"
authors = ["Tomoaki Kawada <tcppjp@gmail.com>"]

[dependencies]
clap = "2.31.2"
nom = { version = "3.2.1", features = ["verbose-errors"] }
lazy_static = "1.0.0"
unicase = "2.1.0"
num-integer = "0.1.34"
num-traits = "0.1.37"
